// Package checkpoints exposes the committed extraction corpus
// (checkpoints.json) plus the generated pending-stub list (stubs.gen.go).
// Both are regenerated by `validator extract --write`.
package checkpoints

import (
	"encoding/json"
	"fmt"

	_ "embed"

	spec "exchange-testspec/spec"
)

//go:embed checkpoints.json
var corpusJSON []byte

// Load parses the committed corpus snapshot into a spec.Corpus.
func Load() (*spec.Corpus, error) {
	var c spec.Corpus
	if err := json.Unmarshal(corpusJSON, &c); err != nil {
		return nil, fmt.Errorf("checkpoints.json: %w", err)
	}
	return &c, nil
}
