// Code generated by `validator extract --write`. DO NOT EDIT.

package checkpoints

// PendingStubs lists extracted checkpoint IDs with no registered
// implementation at generation time — the scaffold the runner reports
// as pending/missing.
var PendingStubs = []string{}
