// Code generated by `validator extract --write`. DO NOT EDIT.

package checkpoints

// PendingStubs lists extracted checkpoint IDs with no registered
// implementation at generation time — the scaffold the runner reports
// as pending/missing.
var PendingStubs = []string{
	"P08.5-T8.5.3.1-C1", // Phase-08.5-PreProduction-LoadTest.md:45 [75k/sec staging gate — defined first, validated against spe…]
	"P24-T24.3.1-C1",    // Phase-24-Backoffice-Settlement.md:43 [nostro/vostro account management]
	"P24-T24.3.2-C1",    // Phase-24-Backoffice-Settlement.md:71 [nostro/vostro reconciliation]
	"P24-T24.3.3-C1",    // Phase-24-Backoffice-Settlement.md:95 [settlement confirmation tracking]
	"P24-T24.3.4-C1",    // Phase-24-Backoffice-Settlement.md:119 [SWIFT message tracking]
	"P24-T24.3.5-C1",    // Phase-24-Backoffice-Settlement.md:146 [compliance reporting]
	"P24-T24.3.6-C1",    // Phase-24-Backoffice-Settlement.md:170 [failed settlement handling]
	"P24-T24.3.7-C1",    // Phase-24-Backoffice-Settlement.md:198 [PB give-up reconciliation]
	"P24-T24.3.8-C1",    // Phase-24-Backoffice-Settlement.md:224 [CLS PvP settlement service]
	"P24-T24.3.9-C1",    // Phase-24-Backoffice-Settlement.md:251 [bilateral netting + SSI (§17.7, §24 #155)]
	"P24-T24.3.10-C1",   // Phase-24-Backoffice-Settlement.md:278 [bunched-order average-price allocation (§17.8, §24 #172)]
	"P24-T24.3.11-C1",   // Phase-24-Backoffice-Settlement.md:310 [client-money segregation + daily reconciliation (§17.9, §24…]
	"P24-T24.3.12-C1",   // Phase-24-Backoffice-Settlement.md:341 [Bank statement ingestion and reconciliation parser (§17.10,…]
	"P24-T24.3.13-C1",   // Phase-24-Backoffice-Settlement.md:368 [CSDR settlement discipline regime (§17.6 extension, §24 #19…]
	"P24-T24.3.14-C1",   // Phase-24-Backoffice-Settlement.md:396 [PB credit restitution on settlement failure (§13.7 extensio…]
	"P24-T24.3.15-C1",   // Phase-24-Backoffice-Settlement.md:427 [post-trade allocation]
	"P24-T24.3.16-C1",   // Phase-24-Backoffice-Settlement.md:443 [CLS settlement mismatch quarantine and client-money shortfa…]
	"P24-T24.3.17-C1",   // Phase-24-Backoffice-Settlement.md:470 [venue own funds, contingent capital, insurance cover and st…]
	"P24-T24.3.18-C1",   // Phase-24-Backoffice-Settlement.md:498 [independent client-money audit and segregation certificatio…]
	"P24-T24.3.19-C1",   // Phase-24-Backoffice-Settlement.md:522 [break lifecycle with suspense SLA, funded nostro with backu…]
	"P24-T24.3.20-C1",   // Phase-24-Backoffice-Settlement.md:549 [banking rail cut-off evaluation and automatic value-date ro…]
	"P24-T24.3.21-C1",   // Phase-24-Backoffice-Settlement.md:576 [unmatched bank deposit suspense GL routing and compliance q…]
}
