#pragma once

// Task 2.3.2 — outbound IPC publisher (spec §3.7.6, Task 2.3.7 seam).
//
// Serializes engine events as FlatBuffers `Event` envelopes per
// core/proto/exchange.fbs (regenerated by the build into
// proto/gen/exchange_generated.h — the build-tree copy wins the include
// path so it always matches the installed flatbuffers runtime):
//
//   publish_trade()         -> Event{ TradeFill }      (per fill)
//   publish_order_cancel()  -> Event{ OrderCancel }    (terminal + rejects;
//                                                       the schema has no
//                                                       dedicated reject
//                                                       table — OrderCancel
//                                                       is the unsolicited
//                                                       terminal notice)
//   publish_book_snapshot() -> Event{ BookSnapshot }   (aggregated depth)
//
// Framing: slot/record length is carried by the transport (ShmRing slot
// header / Aeron frame), so buffers are plain Finish() roots — the Go side
// reads them with wire.GetRootAsEvent (services/internal/ipc/messages.go).
//
// Zero-alloc hot path: a single reusable FlatBufferBuilder is pre-grown at
// construction to fit the worst-case full-depth BookSnapshot (2*4096
// levels); Reset() keeps capacity, and offset staging uses a fixed member
// array — no heap traffic after the constructor.
//
// send() failure = backpressure: counted in drops_ and reported to the
// caller (EnginePump owns ENGINE_OVERLOAD accounting — see
// EnginePump::send_outbound/note_outbound_drop).

#include <cstddef>
#include <cstdint>

#if __has_include("exchange_generated.h") && \
    __has_include(<flatbuffers/flatbuffers.h>)
#define EXCH_IPC_FLATBUFFERS 1
#include "exchange_generated.h"
#endif

#include "book/OrderBook.hpp"
#include "ipc/TraceContext.hpp"  // Task 9.3.11 — EXCTRACE echo seam

namespace exch {

class IpcChannel;

class IpcPublisher {
public:
    // out may be nullptr — every publish then reports false (dropped).
    // builder_capacity defaults to cover a full-depth snapshot.
    explicit IpcPublisher(IpcChannel* out,
                          std::size_t builder_capacity = 1u << 20) noexcept
        : out_(out)
#ifdef EXCH_IPC_FLATBUFFERS
          ,
          builder_(builder_capacity)
#endif
    {
    }

    IpcPublisher(const IpcPublisher&) = delete;
    IpcPublisher& operator=(const IpcPublisher&) = delete;

    // One TradeFill per executed fill. engine_seq = book_seq at the fill.
    [[nodiscard]] bool publish_trade(uint64_t trade_id, uint64_t buy_order_id,
                                     uint64_t sell_order_id,
                                     int64_t price_ticks, int64_t qty_units,
                                     uint64_t engine_seq,
                                     uint64_t ts_ns) noexcept;

    // Terminal notice for cancels + rejects (schema has no reject table —
    // OrderCancel is the closest envelope; engine-side last_reject() carries
    // the specific code for logs/tests). `reason` is the kWalCancelReason*
    // family (0 = user/unspecified; 7 = OCO sibling cancellation — the
    // order-service maps it to the OCO_SIBLING_CANCEL_RACE path).
    [[nodiscard]] bool publish_order_cancel(uint64_t order_id,
                                            uint64_t account_id,
                                            uint64_t ts_ns,
                                            uint8_t reason) noexcept;
    // Convenience overload for callers without a cancel reason (reason=0).
    [[nodiscard]] bool publish_order_cancel(uint64_t order_id,
                                            uint64_t account_id,
                                            uint64_t ts_ns) noexcept {
        return publish_order_cancel(order_id, account_id, ts_ns, 0);
    }

    // Aggregated top-N snapshot per the L2 wire contract (spec §10.2:
    // "Top 20 price levels per side"). Phase-08 Task 8.3.3: previously
    // serialized all levels (up to kMaxLevels/side), which both overflowed
    // the 1024B shm slot (every deep-book frame dropped at send) and spent
    // O(depth) on the matching thread per book change.
    static constexpr uint32_t kWireDepthLevels = 20;
    [[nodiscard]] bool publish_book_snapshot(const OrderBook& book,
                                             uint32_t instrument_id,
                                             uint64_t ts_ns) noexcept;

    // Phase-15 — auction phase transition / indicative clearing update
    // (spec §7.3). `phase` is the engine's kAuctionPhase* code; `signal`
    // distinguishes indicative updates (0) from terminal strikes (1=uncross
    // committed, 2=extended, 3=failed/quarantined, 4=crossed-book halt).
    [[nodiscard]] bool publish_auction_event(uint32_t instrument_id,
                                             uint64_t auction_id,
                                             uint8_t phase, uint8_t signal,
                                             int64_t indicative_price,
                                             int64_t indicative_qty,
                                             int64_t imbalance,
                                             int64_t deadline_ns,
                                             int64_t cleared_qty,
                                             uint64_t ts_ns) noexcept;

    // Task 9.3.11 — trace-echo binding (spec §19.12 Aeron header format):
    // while the owning EnginePump's TraceSlot is armed (dispatch window of
    // a traced inbound command), emit() prefixes the 64B EXCTRACE block
    // verbatim onto the wire so the Go consumer continues the trace with
    // tracing.ExtractAeronTrace. Frames emitted outside the window keep the
    // legacy unprefixed shape; an oversized payload ships untraced rather
    // than dropped (metadata never outranks send correctness).
    void set_trace_slot(const TraceSlot* slot) noexcept {
        trace_slot_ = slot;
    }

    [[nodiscard]] bool bound() const noexcept { return out_ != nullptr; }
    [[nodiscard]] uint64_t published() const noexcept { return published_; }
    [[nodiscard]] uint64_t drops() const noexcept { return drops_; }
    [[nodiscard]] uint64_t pub_seq() const noexcept { return pub_seq_; }

private:
    IpcChannel* out_;
    uint64_t pub_seq_ = 0;
    uint64_t published_ = 0;
    uint64_t drops_ = 0;
    const TraceSlot* trace_slot_ = nullptr;  // Task 9.3.11 echo binding

    // Staging for [EXCTRACE block][Event] composition — covers every frame
    // that fits a transport slot; larger payloads ship untraced.
    static constexpr uint32_t kTraceStageBytes = 16 * 1024;

#ifdef EXCH_IPC_FLATBUFFERS
    flatbuffers::FlatBufferBuilder builder_;
    uint8_t trace_stage_[kTraceStageBytes] = {};
    // Offset staging for snapshot level vectors (no heap).
    flatbuffers::Offset<exc::wire::PriceLevel>
        level_off_[2 * OrderBook::kMaxLevels];
    [[nodiscard]] bool emit(flatbuffers::Offset<exc::wire::Event> ev) noexcept;
#endif
};

}  // namespace exch
