#pragma once

// Task 2.3.2 — outbound IPC publisher (spec §3.7.6, Task 2.3.7 seam).
//
// Serializes engine events as FlatBuffers `Event` envelopes per
// core/proto/exchange.fbs (regenerated by the build into
// proto/gen/exchange_generated.h — the build-tree copy wins the include
// path so it always matches the installed flatbuffers runtime):
//
//   publish_trade()         -> Event{ TradeFill }      (per fill)
//   publish_order_cancel()  -> Event{ OrderCancel }    (terminal + rejects;
//                                                       the schema has no
//                                                       dedicated reject
//                                                       table — OrderCancel
//                                                       is the unsolicited
//                                                       terminal notice)
//   publish_book_snapshot() -> Event{ BookSnapshot }   (aggregated depth)
//
// Framing: slot/record length is carried by the transport (ShmRing slot
// header / Aeron frame), so buffers are plain Finish() roots — the Go side
// reads them with wire.GetRootAsEvent (services/internal/ipc/messages.go).
//
// Zero-alloc hot path: a single reusable FlatBufferBuilder is pre-grown at
// construction to fit the worst-case full-depth BookSnapshot (2*4096
// levels); Reset() keeps capacity, and offset staging uses a fixed member
// array — no heap traffic after the constructor.
//
// send() failure = backpressure: counted in drops_ and reported to the
// caller (EnginePump owns ENGINE_OVERLOAD accounting — see
// EnginePump::send_outbound/note_outbound_drop).

#include <cstddef>
#include <cstdint>

#if __has_include("exchange_generated.h") && \
    __has_include(<flatbuffers/flatbuffers.h>)
#define EXCH_IPC_FLATBUFFERS 1
#include "exchange_generated.h"
#endif

#include "book/OrderBook.hpp"

namespace exch {

class IpcChannel;

class IpcPublisher {
public:
    // out may be nullptr — every publish then reports false (dropped).
    // builder_capacity defaults to cover a full-depth snapshot.
    explicit IpcPublisher(IpcChannel* out,
                          std::size_t builder_capacity = 1u << 20) noexcept
        : out_(out)
#ifdef EXCH_IPC_FLATBUFFERS
          ,
          builder_(builder_capacity)
#endif
    {
    }

    IpcPublisher(const IpcPublisher&) = delete;
    IpcPublisher& operator=(const IpcPublisher&) = delete;

    // One TradeFill per executed fill. engine_seq = book_seq at the fill.
    [[nodiscard]] bool publish_trade(uint64_t trade_id, uint64_t buy_order_id,
                                     uint64_t sell_order_id,
                                     int64_t price_ticks, int64_t qty_units,
                                     uint64_t engine_seq,
                                     uint64_t ts_ns) noexcept;

    // Terminal notice for cancels + rejects (schema has no reject table —
    // OrderCancel is the closest envelope; engine-side last_reject() carries
    // the specific code for logs/tests).
    [[nodiscard]] bool publish_order_cancel(uint64_t order_id,
                                            uint64_t account_id,
                                            uint64_t ts_ns) noexcept;

    // Aggregated top-N snapshot per the L2 wire contract (spec §10.2:
    // "Top 20 price levels per side"). Phase-08 Task 8.3.3: previously
    // serialized all levels (up to kMaxLevels/side), which both overflowed
    // the 1024B shm slot (every deep-book frame dropped at send) and spent
    // O(depth) on the matching thread per book change.
    static constexpr uint32_t kWireDepthLevels = 20;
    [[nodiscard]] bool publish_book_snapshot(const OrderBook& book,
                                             uint32_t instrument_id,
                                             uint64_t ts_ns) noexcept;

    [[nodiscard]] bool bound() const noexcept { return out_ != nullptr; }
    [[nodiscard]] uint64_t published() const noexcept { return published_; }
    [[nodiscard]] uint64_t drops() const noexcept { return drops_; }
    [[nodiscard]] uint64_t pub_seq() const noexcept { return pub_seq_; }

private:
    IpcChannel* out_;
    uint64_t pub_seq_ = 0;
    uint64_t published_ = 0;
    uint64_t drops_ = 0;

#ifdef EXCH_IPC_FLATBUFFERS
    flatbuffers::FlatBufferBuilder builder_;
    // Offset staging for snapshot level vectors (no heap).
    flatbuffers::Offset<exc::wire::PriceLevel>
        level_off_[2 * OrderBook::kMaxLevels];
    [[nodiscard]] bool emit(flatbuffers::Offset<exc::wire::Event> ev) noexcept;
#endif
};

}  // namespace exch
