// Task 5.3.8 — full OpenAPI 3.1 document generated from the route
// registry.
//
// OpenAPIDocument consumes the *registry* (routes + metadata + body
// schemas) and errs.Default (every registered §23 code lands in
// components.x-error-codes) — the doc is derivable, never hand-
// maintained. `go run ./cmd/openapi-gen` regenerates the checked-in
// artifact at docs/openapi/openapi.json; the gateway serves the same
// document live at GET /api/v1/openapi.json.
package api

import (
	"net/http"
	"regexp"
	"sort"
	"strings"

	"exchange/internal/errs"
	"exchange/internal/gateway"
)

// OpenAPIDocument builds the OpenAPI 3.1 document for the registered
// route table. version is the gateway's semantic build (X-API-Version).
func OpenAPIDocument(routes []gateway.Route, reg *errs.Registry, version string) map[string]any {
	if version == "" {
		version = "1.0.0"
	}
	paths := map[string]any{}
	for _, rt := range routes {
		item, _ := paths[rt.Path].(map[string]any)
		if item == nil {
			item = map[string]any{}
			paths[rt.Path] = item
		}
		method := strings.ToLower(rt.Method)
		if rt.Method == "WS" {
			method = "get" // upgrade handshake is GET
		}
		item[method] = openAPIOperation(rt, method)
	}

	// The registry is the error-code source of truth — emit the whole
	// table under components so consumers can codegen error handling.
	codes := reg.All()
	codeRows := make([]map[string]any, 0, len(codes))
	for _, c := range codes {
		row := map[string]any{
			"code":        c.Code,
			"http_status": c.HTTPStatus,
			"description": c.Description,
		}
		if c.Owner != "" {
			row["owner"] = c.Owner
		}
		if c.AliasOf != "" {
			row["alias_of"] = c.AliasOf
		}
		if c.SupersededBy != "" {
			row["superseded_by"] = c.SupersededBy
		}
		if c.Reserved {
			row["reserved"] = true
		}
		codeRows = append(codeRows, row)
	}

	return map[string]any{
		"openapi":           "3.1.0",
		"jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
		"info": map[string]any{
			"title":   "Exchange Order Gateway API",
			"version": version,
			"description": "Fiat-only FOREX exchange — registry-generated contract " +
				"(Phase-05 Tasks 5.3.7/5.3.8). Every route, auth requirement and " +
				"error code is derived from the route registry and the §23 error " +
				"code registry; the document is regenerated by `go run ./cmd/openapi-gen`.",
		},
		"servers": []map[string]any{
			{"url": "/", "description": "this gateway"},
		},
		"externalDocs": map[string]any{
			"description": "Developer portal (Swagger UI) & migration guide",
			"url":         "/developer",
		},
		"paths": paths,
		"components": map[string]any{
			"securitySchemes": map[string]any{
				"bearerAuth": map[string]any{
					"type": "http", "scheme": "bearer", "bearerFormat": "JWT",
					"description": "JWT access token (15min TTL) or OAuth2 client-credentials grant",
				},
				"apiKeyAuth": map[string]any{
					"type": "apiKey", "in": "header", "name": "X-API-KEY",
					"description": "API key id; requests are HMAC-SHA256 or Ed25519/RSA signed per spec §8.1/§8.8",
				},
				"oauth2": map[string]any{
					"type": "oauth2",
					"flows": map[string]any{
						"clientCredentials": map[string]any{
							"tokenUrl": "/api/v1/auth/token",
							"scopes":   map[string]string{}, // scope vocabulary is the x-auth matrix
						},
					},
				},
			},
			"schemas": map[string]any{
				"Problem": map[string]any{
					"type":     "object",
					"required": []string{"type", "error", "message", "status", "timestamp"},
					"properties": map[string]any{
						"type":        map[string]any{"type": "string", "enum": []string{"error"}},
						"error":       map[string]any{"type": "string", "description": "spec §23 machine-readable code (see components.x-error-codes)"},
						"message":     map[string]any{"type": "string"},
						"status":      map[string]any{"type": "integer"},
						"request_id":  map[string]any{"type": "string"},
						"timestamp":   map[string]any{"type": "string", "format": "date-time"},
						"retry_after": map[string]any{"type": "integer"},
						"details":     map[string]any{"type": "object"},
					},
				},
			},
			"responses": map[string]any{
				"Problem": map[string]any{
					"description": "RFC 7807 error envelope (spec §8.7); `error` is a §23 code — full table under components.x-error-codes",
					"content": map[string]any{
						"application/problem+json": map[string]any{
							"schema": map[string]any{"$ref": "#/components/schemas/Problem"},
						},
					},
				},
			},
			"x-error-codes": codeRows,
		},
	}
}

// operationID builds a stable operationId: METHOD + path tokens.
var opIDRe = regexp.MustCompile(`[^a-zA-Z0-9]+`)

func operationID(rt gateway.Route) string {
	id := strings.ToLower(rt.Method) + opIDRe.ReplaceAllString(rt.Path, "_")
	return strings.Trim(id, "_")
}

// tagFor groups an operation under its first meaningful path segment.
func tagFor(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	switch {
	case len(parts) >= 3 && parts[0] == "api":
		return parts[2]
	case len(parts) >= 1:
		return parts[0]
	}
	return "meta"
}

// openAPIOperation renders one route as an OpenAPI operation.
func openAPIOperation(rt gateway.Route, method string) map[string]any {
	op := map[string]any{
		"operationId": operationID(rt),
		"summary":     rt.Description,
		"tags":        []string{tagFor(rt.Path)},
		// Registry metadata — the machine-readable contract for CI,
		// RBAC matrix and rate-weight consumers.
		"x-owner":        rt.Owner,
		"x-status":       string(rt.Status),
		"x-rate-tier":    rt.RateTier,
		"x-weight":       max(rt.Weight, 1),
		"x-dual-control": rt.DualControl,
		"x-env":          rt.Env,
		"x-auth": map[string]any{
			"required": rt.Auth.Required,
			"role":     rt.Auth.Role,
			"scopes":   rt.Auth.Scopes,
			"methods":  rt.Auth.Methods,
		},
		"responses": map[string]any{
			"200":     map[string]any{"description": "success"},
			"default": map[string]any{"$ref": "#/components/responses/Problem"},
		},
	}
	if rt.Status == gateway.StatusStub {
		op["description"] = "Registered but not yet implemented by its owning phase — serves 501 NOT_IMPLEMENTED (spec §8.4 registration-completeness invariant)."
	}
	// Path parameters from {name} segments.
	params := []map[string]any{}
	for _, seg := range strings.Split(rt.Path, "/") {
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			name := strings.Trim(seg, "{}")
			params = append(params, map[string]any{
				"name":     name,
				"in":       "path",
				"required": true,
				"schema":   map[string]any{"type": "string"},
			})
		}
	}
	if len(params) > 0 {
		op["parameters"] = params
	}
	// Auth → security requirement + scope documentation.
	if rt.Auth.Required {
		schemes := rt.Auth.Methods
		if len(schemes) == 0 {
			schemes = []string{gateway.AuthJWT, gateway.AuthHMAC, gateway.AuthOAuth2}
		}
		var reqs []map[string]any
		for _, m := range schemes {
			switch m {
			case gateway.AuthJWT:
				reqs = append(reqs, map[string]any{"bearerAuth": rt.Auth.Scopes})
			case gateway.AuthHMAC:
				reqs = append(reqs, map[string]any{"apiKeyAuth": rt.Auth.Scopes})
			case gateway.AuthOAuth2:
				reqs = append(reqs, map[string]any{"oauth2": rt.Auth.Scopes})
			}
		}
		if len(reqs) > 0 {
			op["security"] = reqs
		}
		if rt.Auth.Role != "" {
			op["x-rbac-role"] = rt.Auth.Role
		}
	}
	// Centralized BodySchema → requestBody JSON schema.
	if rt.Schema != nil && (rt.Method == http.MethodPost || rt.Method == http.MethodPut ||
		rt.Method == http.MethodPatch || rt.Method == http.MethodDelete) {
		props := map[string]any{}
		for field, kind := range rt.Schema.Fields {
			props[field] = map[string]any{"type": kind}
		}
		schema := map[string]any{"type": "object", "properties": props}
		if len(rt.Schema.Required) > 0 {
			req := append([]string{}, rt.Schema.Required...)
			sort.Strings(req)
			schema["required"] = req
		}
		op["requestBody"] = map[string]any{
			"required": true,
			"content": map[string]any{
				"application/json": map[string]any{"schema": schema},
			},
		}
	}
	return op
}

// DocCount sanity-checks the generated document (used by openapi-gen and
// tests): returns (pathCount, operationCount).
func DocCount(doc map[string]any) (int, int) {
	paths, _ := doc["paths"].(map[string]any)
	ops := 0
	for _, item := range paths {
		if m, ok := item.(map[string]any); ok {
			for k := range m {
				if k != "parameters" {
					ops++
				}
			}
		}
	}
	return len(paths), ops
}
