// Measurement harness for Task 9.3.10 AC:
// "Cancel-exempt priority lane processes within 100µs during shedding
// — zero drops under any load condition."
//
// The lane under test is the real middleware path: Shedding() →
// ShouldShed → ShedExempt (ctx marker / X-Exc-Priority header / REST
// DELETE shape). Synthetic shed load is generated by background
// goroutines hammering ShouldShed with shed-eligible requests while
// the shedder is pinned at the worst-case posture (stage 3 + the
// §2.7 95% ENGINE_OVERLOAD watermark) — the shared atomic counters
// are under contention the whole time.
//
// Numbers are reported via b.ReportMetric / t.Logf; the test asserts
// the 100µs p99 bound and the zero-drop contract so a regression
// (or weaker hardware) surfaces honestly.
package middleware

import (
	"net/http"
	"net/http/httptest"
	"runtime"
	"sort"
	"sync/atomic"
	"testing"
	"time"

	"exchange/internal/ratelimit"
)

// cancelLaneBound is the Task 9.3.10 item-7 bound under measurement.
const cancelLaneBound = 100 * time.Microsecond

// overloadedShedder pins the shedder at stage 3 + overload — the worst
// posture the exempt lane must cut through.
func overloadedShedder() *Shedder {
	s := NewShedder(ShedConfig{
		Depth:    func() int64 { return 970 },
		Capacity: 1000,
	})
	s.Sample()
	if !s.Overload() || s.Stage() != 3 {
		panic("harness: shedder not pinned at overload/stage-3")
	}
	return s
}

// discardRW is a zero-alloc ResponseWriter — the measurement targets
// the admission lane, not httptest recorder internals.
type discardRW struct {
	h    http.Header
	code int
}

func (d *discardRW) Header() http.Header {
	if d.h == nil {
		d.h = http.Header{}
	}
	return d.h
}
func (d *discardRW) Write(b []byte) (int, error) { return len(b), nil }
func (d *discardRW) WriteHeader(c int)           { d.code = c }

// shedLoad saturates the shedder's shared atomics with shed-eligible
// traffic until stop is closed. Returns the number of shed requests.
func shedLoad(s *Shedder, workers int, stop <-chan struct{}) *atomic.Uint64 {
	shed := &atomic.Uint64{}
	req := httptest.NewRequest(http.MethodPost, "/api/v1/orders", nil)
	for i := 0; i < workers; i++ {
		go func() {
			for {
				select {
				case <-stop:
					return
				default:
					if s.ShouldShed(req, ratelimit.TierPublic) {
						shed.Add(1)
					}
				}
			}
		}()
	}
	return shed
}

// cancelLaneHandler wraps the production middleware over a trivial
// 200 handler — measuring admission + dispatch, the "processes within
// 100µs of receipt" seam.
func cancelLaneHandler(s *Shedder) http.Handler {
	emit := func(w http.ResponseWriter, _ *http.Request, _, _ string, _ map[string]any) {
		w.WriteHeader(http.StatusServiceUnavailable)
	}
	return Shedding(s, ShedOptions{Emit: emit})(
		http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.WriteHeader(http.StatusOK)
		}))
}

func percentiles(lats []time.Duration) (p50, p99, max time.Duration) {
	cp := make([]time.Duration, len(lats))
	copy(cp, lats)
	sort.Slice(cp, func(i, j int) bool { return cp[i] < cp[j] })
	if len(cp) == 0 {
		return 0, 0, 0
	}
	return cp[len(cp)/2], cp[(len(cp)*99)/100], cp[len(cp)-1]
}

// TestCancelExemptLaneLatencyUnderShed is the deterministic harness:
// 20k measured cancel admissions through the real middleware while
// shed load saturates the shared counters at the overload watermark.
// Asserts the zero-drop contract and reports/asserts p99 ≤ 100µs.
func TestCancelExemptLaneLatencyUnderShed(t *testing.T) {
	s := overloadedShedder()
	h := cancelLaneHandler(s)

	stop := make(chan struct{})
	workers := runtime.GOMAXPROCS(0)
	if workers > 8 {
		workers = 8
	}
	shed := shedLoad(s, workers, stop)
	defer close(stop)

	const n = 20_000
	cases := []struct {
		name string
		req  *http.Request
	}{
		{"rest-delete", httptest.NewRequest(http.MethodDelete, "/api/v1/orders/ord-1", nil)},
		{"rest-mass-cancel", httptest.NewRequest(http.MethodPost, "/api/v1/admin/orders/mass-cancel", nil)},
		{"fix-header-tagged", func() *http.Request {
			r := httptest.NewRequest(http.MethodPost, "/api/v1/orders/cancel", nil)
			r.Header.Set(HeaderPriority, PriorityCancelExempt)
			return r
		}()},
	}
	for _, c := range cases {
		lats := make([]time.Duration, 0, n)
		drops := 0
		rw := &discardRW{}
		for i := 0; i < n; i++ {
			rw.code = 0
			start := time.Now()
			h.ServeHTTP(rw, c.req)
			lats = append(lats, time.Since(start))
			if rw.code != http.StatusOK {
				drops++
			}
		}
		p50, p99, max := percentiles(lats)
		t.Logf("%s: n=%d drops=%d p50=%s p99=%s max=%s (bound %s)",
			c.name, n, drops, p50, p99, max, cancelLaneBound)
		if drops != 0 {
			t.Errorf("%s: %d cancel requests shed — zero-drop contract violated", c.name, drops)
		}
		if p99 > cancelLaneBound {
			t.Errorf("%s: p99 %s exceeds the 100µs cancel-lane bound", c.name, p99)
		}
	}
	t.Logf("background shed load: %d requests shed during measurement", shed.Load())
}

// BenchmarkCancelExemptLaneAdmission reports p50/p99/max latency
// (nanoseconds, custom metrics) for one cancel admission through the
// production middleware under concurrent shed load at overload.
func BenchmarkCancelExemptLaneAdmission(b *testing.B) {
	s := overloadedShedder()
	h := cancelLaneHandler(s)

	stop := make(chan struct{})
	defer close(stop)
	shedLoad(s, 4, stop)

	req := httptest.NewRequest(http.MethodDelete, "/api/v1/orders/ord-1", nil)
	rw := &discardRW{}

	// Cap the latency slice so large -benchtime runs don't exhaust
	// memory; 1<<20 samples is plenty for stable percentiles.
	const capN = 1 << 20
	lats := make([]time.Duration, 0, capN)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		rw.code = 0
		start := time.Now()
		h.ServeHTTP(rw, req)
		el := time.Since(start)
		if len(lats) < capN {
			lats = append(lats, el)
		}
		if rw.code != http.StatusOK {
			b.Fatal("cancel request shed — zero-drop contract violated")
		}
	}
	b.StopTimer()
	p50, p99, max := percentiles(lats)
	b.ReportMetric(float64(p50.Nanoseconds()), "p50-ns")
	b.ReportMetric(float64(p99.Nanoseconds()), "p99-ns")
	b.ReportMetric(float64(max.Nanoseconds()), "max-ns")
}
