server_name: nats-2
listen: 4222
http: 8222

jetstream {
  store_dir: /data
  max_file_store: 10GB
  max_mem_store: 1GB
}

cluster {
  name: exc-jetstream
  listen: 0.0.0.0:6222
  routes: [
    nats-route://nats-1:6222
    nats-route://nats-2:6222
    nats-route://nats-3:6222
  ]
}
