// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Outbound: auction phase transition / indicative update — Phase-15
/// (spec §7.3 reopening call auction). Emitted on every committed phase
/// transition and when the indicative clearing pair (price,qty) changes
/// during CALL accumulation.
///   phase:  0=CALL 1=EXTEND 2=UNCROSS 3=CANCEL 4=QUARANTINE
///           5=STRIKE_FAILED (deadline struck, no clearing price formed)
///   signal: 0=indicative update, 1=uncross committed, 2=deadline extended,
///           3=clearing failed/quarantined, 4=crossed-book quarantine
///   auction_id: opaque id of the armed CALL (the armed deadline ns value).
///   imbalance: signed buy-minus-sell eligible qty at the indicative price.
type AuctionEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsAuctionEvent(buf []byte, offset flatbuffers.UOffsetT) *AuctionEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuctionEvent{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AuctionEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuctionEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AuctionEvent) InstrumentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateInstrumentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *AuctionEvent) AuctionId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateAuctionId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *AuctionEvent) Phase() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutatePhase(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *AuctionEvent) Signal() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateSignal(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *AuctionEvent) IndicativePrice() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateIndicativePrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *AuctionEvent) IndicativeQty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateIndicativeQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *AuctionEvent) Imbalance() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateImbalance(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *AuctionEvent) DeadlineNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateDeadlineNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *AuctionEvent) ClearedQty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AuctionEvent) MutateClearedQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func AuctionEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func AuctionEventAddInstrumentId(builder *flatbuffers.Builder, instrumentId uint32) {
	builder.PrependUint32Slot(0, instrumentId, 0)
}
func AuctionEventAddAuctionId(builder *flatbuffers.Builder, auctionId uint64) {
	builder.PrependUint64Slot(1, auctionId, 0)
}
func AuctionEventAddPhase(builder *flatbuffers.Builder, phase byte) {
	builder.PrependByteSlot(2, phase, 0)
}
func AuctionEventAddSignal(builder *flatbuffers.Builder, signal byte) {
	builder.PrependByteSlot(3, signal, 0)
}
func AuctionEventAddIndicativePrice(builder *flatbuffers.Builder, indicativePrice int64) {
	builder.PrependInt64Slot(4, indicativePrice, 0)
}
func AuctionEventAddIndicativeQty(builder *flatbuffers.Builder, indicativeQty int64) {
	builder.PrependInt64Slot(5, indicativeQty, 0)
}
func AuctionEventAddImbalance(builder *flatbuffers.Builder, imbalance int64) {
	builder.PrependInt64Slot(6, imbalance, 0)
}
func AuctionEventAddDeadlineNs(builder *flatbuffers.Builder, deadlineNs int64) {
	builder.PrependInt64Slot(7, deadlineNs, 0)
}
func AuctionEventAddClearedQty(builder *flatbuffers.Builder, clearedQty int64) {
	builder.PrependInt64Slot(8, clearedQty, 0)
}
func AuctionEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
