// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// One leg of a cross-shard basket order (Task 2.3.8/2.3.25, spec §2.2a).
/// `order_id` is the leg's client-visible order id (the gateway allocates it
/// like any order id); `limit_price` = 0 executes the leg as a pure market
/// leg under the optimistic path.
type BasketLeg struct {
	_tab flatbuffers.Table
}

func GetRootAsBasketLeg(buf []byte, offset flatbuffers.UOffsetT) *BasketLeg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BasketLeg{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BasketLeg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BasketLeg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BasketLeg) ShardId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketLeg) MutateShardId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *BasketLeg) InstrumentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketLeg) MutateInstrumentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *BasketLeg) OrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketLeg) MutateOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *BasketLeg) Side() Side {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return Side(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *BasketLeg) MutateSide(n Side) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *BasketLeg) Qty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketLeg) MutateQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *BasketLeg) LimitPrice() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketLeg) MutateLimitPrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func BasketLegStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func BasketLegAddShardId(builder *flatbuffers.Builder, shardId uint32) {
	builder.PrependUint32Slot(0, shardId, 0)
}
func BasketLegAddInstrumentId(builder *flatbuffers.Builder, instrumentId uint32) {
	builder.PrependUint32Slot(1, instrumentId, 0)
}
func BasketLegAddOrderId(builder *flatbuffers.Builder, orderId uint64) {
	builder.PrependUint64Slot(2, orderId, 0)
}
func BasketLegAddSide(builder *flatbuffers.Builder, side Side) {
	builder.PrependByteSlot(3, byte(side), 0)
}
func BasketLegAddQty(builder *flatbuffers.Builder, qty int64) {
	builder.PrependInt64Slot(4, qty, 0)
}
func BasketLegAddLimitPrice(builder *flatbuffers.Builder, limitPrice int64) {
	builder.PrependInt64Slot(5, limitPrice, 0)
}
func BasketLegEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
