// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Outbound: terminal basket outcome (OptimisticShardCoordinator result).
/// Emitted once per op when it reaches a terminal state; the gateway routes
/// it to the basket status projection.
///   status: OptStatus ordinal (1=Matching 2=Committed 3=Unwinding
///           4=Compensated 5=Failed 6=Rejected) — only terminal values
///           (2/4/5/6) are emitted.
///   code:   OptCode ordinal (see OptimisticShardCoordinator.hpp).
type BasketResult struct {
	_tab flatbuffers.Table
}

func GetRootAsBasketResult(buf []byte, offset flatbuffers.UOffsetT) *BasketResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BasketResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BasketResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BasketResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BasketResult) OpIdHi() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateOpIdHi(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *BasketResult) OpIdLo() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateOpIdLo(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *BasketResult) AccountId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateAccountId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *BasketResult) Status() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *BasketResult) Code() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateCode(n byte) bool {
	return rcv._tab.MutateByteSlot(12, n)
}

func (rcv *BasketResult) LegCount() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateLegCount(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *BasketResult) LegsFilled() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateLegsFilled(n byte) bool {
	return rcv._tab.MutateByteSlot(16, n)
}

func (rcv *BasketResult) LegsUnwound() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateLegsUnwound(n byte) bool {
	return rcv._tab.MutateByteSlot(18, n)
}

func (rcv *BasketResult) Slippage() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateSlippage(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *BasketResult) DurationNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketResult) MutateDurationNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func BasketResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func BasketResultAddOpIdHi(builder *flatbuffers.Builder, opIdHi uint64) {
	builder.PrependUint64Slot(0, opIdHi, 0)
}
func BasketResultAddOpIdLo(builder *flatbuffers.Builder, opIdLo uint64) {
	builder.PrependUint64Slot(1, opIdLo, 0)
}
func BasketResultAddAccountId(builder *flatbuffers.Builder, accountId uint64) {
	builder.PrependUint64Slot(2, accountId, 0)
}
func BasketResultAddStatus(builder *flatbuffers.Builder, status byte) {
	builder.PrependByteSlot(3, status, 0)
}
func BasketResultAddCode(builder *flatbuffers.Builder, code byte) {
	builder.PrependByteSlot(4, code, 0)
}
func BasketResultAddLegCount(builder *flatbuffers.Builder, legCount byte) {
	builder.PrependByteSlot(5, legCount, 0)
}
func BasketResultAddLegsFilled(builder *flatbuffers.Builder, legsFilled byte) {
	builder.PrependByteSlot(6, legsFilled, 0)
}
func BasketResultAddLegsUnwound(builder *flatbuffers.Builder, legsUnwound byte) {
	builder.PrependByteSlot(7, legsUnwound, 0)
}
func BasketResultAddSlippage(builder *flatbuffers.Builder, slippage int64) {
	builder.PrependInt64Slot(8, slippage, 0)
}
func BasketResultAddDurationNs(builder *flatbuffers.Builder, durationNs uint64) {
	builder.PrependUint64Slot(9, durationNs, 0)
}
func BasketResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
