// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Inbound: cross-shard basket submit (IMP-PLAN Phase-3 Task 4). Sent to the
/// coordinator shard's `_in` ring — the shard with the LOWEST leg shard_id
/// (Task 2.3.8 election rule; the gateway computes it). Execution goes
/// through the canonical optimistic path (OptimisticShardCoordinator —
/// spec §2.2a supersedes the blocking-2PC hot path); the 2PC coordinator
/// remains the reservation/bookkeeping substrate for its own ctl traffic.
/// op_id is the 128-bit dedup identity (UUID v4 or gateway-minted pair).
type BasketSubmit struct {
	_tab flatbuffers.Table
}

func GetRootAsBasketSubmit(buf []byte, offset flatbuffers.UOffsetT) *BasketSubmit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BasketSubmit{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BasketSubmit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BasketSubmit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BasketSubmit) OpIdHi() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketSubmit) MutateOpIdHi(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *BasketSubmit) OpIdLo() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketSubmit) MutateOpIdLo(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *BasketSubmit) AccountId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BasketSubmit) MutateAccountId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *BasketSubmit) Legs(obj *BasketLeg, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BasketSubmit) LegsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BasketSubmitStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func BasketSubmitAddOpIdHi(builder *flatbuffers.Builder, opIdHi uint64) {
	builder.PrependUint64Slot(0, opIdHi, 0)
}
func BasketSubmitAddOpIdLo(builder *flatbuffers.Builder, opIdLo uint64) {
	builder.PrependUint64Slot(1, opIdLo, 0)
}
func BasketSubmitAddAccountId(builder *flatbuffers.Builder, accountId uint64) {
	builder.PrependUint64Slot(2, accountId, 0)
}
func BasketSubmitAddLegs(builder *flatbuffers.Builder, legs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(legs), 0)
}
func BasketSubmitStartLegsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BasketSubmitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
