// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Outbound: aggregated order-book snapshot for market data fan-out.
type BookSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsBookSnapshot(buf []byte, offset flatbuffers.UOffsetT) *BookSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BookSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BookSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BookSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BookSnapshot) InstrumentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BookSnapshot) MutateInstrumentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *BookSnapshot) Seq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BookSnapshot) MutateSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *BookSnapshot) Bids(obj *PriceLevel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BookSnapshot) BidsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BookSnapshot) Asks(obj *PriceLevel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BookSnapshot) AsksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BookSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func BookSnapshotAddInstrumentId(builder *flatbuffers.Builder, instrumentId uint32) {
	builder.PrependUint32Slot(0, instrumentId, 0)
}
func BookSnapshotAddSeq(builder *flatbuffers.Builder, seq uint64) {
	builder.PrependUint64Slot(1, seq, 0)
}
func BookSnapshotAddBids(builder *flatbuffers.Builder, bids flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(bids), 0)
}
func BookSnapshotStartBidsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BookSnapshotAddAsks(builder *flatbuffers.Builder, asks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(asks), 0)
}
func BookSnapshotStartAsksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BookSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
