// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type EventType byte

const (
	EventTypeNONE         EventType = 0
	EventTypeOrderNew     EventType = 1
	EventTypeOrderCancel  EventType = 2
	EventTypeTradeFill    EventType = 3
	EventTypeBookSnapshot EventType = 4
	EventTypeTimeTick     EventType = 5
	EventTypeOrderAmend   EventType = 6
	EventTypeOcoLink      EventType = 7
	EventTypeAuctionEvent EventType = 8
	EventTypeL3OrderEvent EventType = 9
)

var EnumNamesEventType = map[EventType]string{
	EventTypeNONE:         "NONE",
	EventTypeOrderNew:     "OrderNew",
	EventTypeOrderCancel:  "OrderCancel",
	EventTypeTradeFill:    "TradeFill",
	EventTypeBookSnapshot: "BookSnapshot",
	EventTypeTimeTick:     "TimeTick",
	EventTypeOrderAmend:   "OrderAmend",
	EventTypeOcoLink:      "OcoLink",
	EventTypeAuctionEvent: "AuctionEvent",
	EventTypeL3OrderEvent: "L3OrderEvent",
}

var EnumValuesEventType = map[string]EventType{
	"NONE":         EventTypeNONE,
	"OrderNew":     EventTypeOrderNew,
	"OrderCancel":  EventTypeOrderCancel,
	"TradeFill":    EventTypeTradeFill,
	"BookSnapshot": EventTypeBookSnapshot,
	"TimeTick":     EventTypeTimeTick,
	"OrderAmend":   EventTypeOrderAmend,
	"OcoLink":      EventTypeOcoLink,
	"AuctionEvent": EventTypeAuctionEvent,
	"L3OrderEvent": EventTypeL3OrderEvent,
}

func (v EventType) String() string {
	if s, ok := EnumNamesEventType[v]; ok {
		return s
	}
	return "EventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
