// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Envelope for every IPC message. `type_type` carries the discriminator.
type Event struct {
	_tab flatbuffers.Table
}

func GetRootAsEvent(buf []byte, offset flatbuffers.UOffsetT) *Event {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Event{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Event) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Event) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Event) Seq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *Event) Ts() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Event) MutateTs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Event) TypeType() EventType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return EventType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Event) MutateTypeType(n EventType) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *Event) Type(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func EventStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func EventAddSeq(builder *flatbuffers.Builder, seq uint64) {
	builder.PrependUint64Slot(0, seq, 0)
}
func EventAddTs(builder *flatbuffers.Builder, ts uint64) {
	builder.PrependUint64Slot(1, ts, 0)
}
func EventAddTypeType(builder *flatbuffers.Builder, typeType EventType) {
	builder.PrependByteSlot(2, byte(typeType), 0)
}
func EventAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(type_), 0)
}
func EventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
