// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

/// Outbound: one order-level (L3) lifecycle event — Phase-17 Task 17.3.1,
/// spec §11. Emitted by the matching core ONLY after the triggering
/// mutation is WAL-committed: wal_seq is that row's sequence, giving the
/// read model a 1:1-verifiable L3 <-> journal correlation (spec §24 #318).
/// A single WAL row may produce multiple L3 events sharing its wal_seq
/// (e.g. a TRADE row yields maker + taker Fill events; an ingress row may
/// yield Add + Fill + remainder Cancel); every emitted event then carries
/// the seq of the row that caused it.
///
///   account_hash: stable pseudonym, NEVER the raw account id — salted
///                 FNV-1a-64, see exch::L3Publisher::hash_account
///                 (salt literal "exc.l3.account.v1").
///   qty:          order-level remaining qty AFTER the event (scaled 1e8;
///                 Cancel -> 0; for ICEBERG orders this is the full hidden
///                 reserve remaining, not the visible slice).
///   qty_delta:    signed remaining-qty change applied by this event:
///                 +qty on Add, -fill on Fill, -cancelled remainder on
///                 Cancel, signed delta on a qty Modify, 0 on a
///                 price-only Modify / PEG reprice.
///   price:        order price after the event (scaled 1e8); the fill
///                 print on Fill; the new resting price on a PEG reprice.
///   ref_price:    pending conditional trigger price (stop/trailing-arm
///                 orders) when carried by the triggering WAL row; else 0.
///   seq:          per-instrument monotonic L3 sequence (spec §11.1) —
///                 1-BASED (0 is the flatbuffers absent-field sentinel and
///                 is contract-invalid); assigned at emission and consumed
///                 even when transport send fails, so consumers detect loss
///                 as a gap and resync via snapshot.
///   fill_role:    Fill only: 1 = taker leg, 2 = maker leg, 3 = auction
///                 uncross leg; 0 elsewhere.
///   flags:        bit0 hidden (not L2-visible: hidden flag or PEG),
///                 bit1 pegged, bit2 synthetic venue leg (GSLO paired),
///                 bit3 iceberg order, bit4 detail present (side/price/
///                 qty populated; a Cancel may legitimately carry 0 when
///                 the order context is unresolvable).
///   cancel_reason: Cancel only — kWalCancelReason* code (0 user,
///                 1 expired, 2 STP, 3 FOK unfilled, 4 IOC remainder,
///                 5 slippage, 6 exec-rule, 7 OCO sibling); 0 elsewhere.
///   kind + per-symbol seq + wal_seq let consumers and the §24 #318 audit
///   reconcile L3 against the journal without trusting timestamps.
type L3EventKind byte

const (
	L3EventKindAdd    L3EventKind = 0
	L3EventKindModify L3EventKind = 1
	L3EventKindCancel L3EventKind = 2
	L3EventKindFill   L3EventKind = 3
)

var EnumNamesL3EventKind = map[L3EventKind]string{
	L3EventKindAdd:    "Add",
	L3EventKindModify: "Modify",
	L3EventKindCancel: "Cancel",
	L3EventKindFill:   "Fill",
}

var EnumValuesL3EventKind = map[string]L3EventKind{
	"Add":    L3EventKindAdd,
	"Modify": L3EventKindModify,
	"Cancel": L3EventKindCancel,
	"Fill":   L3EventKindFill,
}

func (v L3EventKind) String() string {
	if s, ok := EnumNamesL3EventKind[v]; ok {
		return s
	}
	return "L3EventKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
