// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type L3OrderEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsL3OrderEvent(buf []byte, offset flatbuffers.UOffsetT) *L3OrderEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &L3OrderEvent{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *L3OrderEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *L3OrderEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *L3OrderEvent) InstrumentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateInstrumentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *L3OrderEvent) Kind() L3EventKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return L3EventKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *L3OrderEvent) MutateKind(n L3EventKind) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *L3OrderEvent) OrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *L3OrderEvent) AccountHash() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateAccountHash(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *L3OrderEvent) Side() Side {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return Side(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *L3OrderEvent) MutateSide(n Side) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func (rcv *L3OrderEvent) Price() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutatePrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *L3OrderEvent) RefPrice() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateRefPrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *L3OrderEvent) Qty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *L3OrderEvent) QtyDelta() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateQtyDelta(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *L3OrderEvent) Seq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func (rcv *L3OrderEvent) WalSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateWalSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(24, n)
}

func (rcv *L3OrderEvent) TradeId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateTradeId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(26, n)
}

func (rcv *L3OrderEvent) FillRole() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateFillRole(n byte) bool {
	return rcv._tab.MutateByteSlot(28, n)
}

func (rcv *L3OrderEvent) Flags() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateFlags(n byte) bool {
	return rcv._tab.MutateByteSlot(30, n)
}

func (rcv *L3OrderEvent) CancelReason() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *L3OrderEvent) MutateCancelReason(n byte) bool {
	return rcv._tab.MutateByteSlot(32, n)
}

func L3OrderEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func L3OrderEventAddInstrumentId(builder *flatbuffers.Builder, instrumentId uint32) {
	builder.PrependUint32Slot(0, instrumentId, 0)
}
func L3OrderEventAddKind(builder *flatbuffers.Builder, kind L3EventKind) {
	builder.PrependByteSlot(1, byte(kind), 0)
}
func L3OrderEventAddOrderId(builder *flatbuffers.Builder, orderId uint64) {
	builder.PrependUint64Slot(2, orderId, 0)
}
func L3OrderEventAddAccountHash(builder *flatbuffers.Builder, accountHash uint64) {
	builder.PrependUint64Slot(3, accountHash, 0)
}
func L3OrderEventAddSide(builder *flatbuffers.Builder, side Side) {
	builder.PrependByteSlot(4, byte(side), 0)
}
func L3OrderEventAddPrice(builder *flatbuffers.Builder, price int64) {
	builder.PrependInt64Slot(5, price, 0)
}
func L3OrderEventAddRefPrice(builder *flatbuffers.Builder, refPrice int64) {
	builder.PrependInt64Slot(6, refPrice, 0)
}
func L3OrderEventAddQty(builder *flatbuffers.Builder, qty int64) {
	builder.PrependInt64Slot(7, qty, 0)
}
func L3OrderEventAddQtyDelta(builder *flatbuffers.Builder, qtyDelta int64) {
	builder.PrependInt64Slot(8, qtyDelta, 0)
}
func L3OrderEventAddSeq(builder *flatbuffers.Builder, seq uint64) {
	builder.PrependUint64Slot(9, seq, 0)
}
func L3OrderEventAddWalSeq(builder *flatbuffers.Builder, walSeq uint64) {
	builder.PrependUint64Slot(10, walSeq, 0)
}
func L3OrderEventAddTradeId(builder *flatbuffers.Builder, tradeId uint64) {
	builder.PrependUint64Slot(11, tradeId, 0)
}
func L3OrderEventAddFillRole(builder *flatbuffers.Builder, fillRole byte) {
	builder.PrependByteSlot(12, fillRole, 0)
}
func L3OrderEventAddFlags(builder *flatbuffers.Builder, flags byte) {
	builder.PrependByteSlot(13, flags, 0)
}
func L3OrderEventAddCancelReason(builder *flatbuffers.Builder, cancelReason byte) {
	builder.PrependByteSlot(14, cancelReason, 0)
}
func L3OrderEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
