// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Inbound: OCO (one-cancels-other) link command — Phase-14 Task 14.3.1,
/// spec §6.2/§6.5. The gateway sends this event on the pair's shard BEFORE
/// either leg's OrderNew, so the engine installs the linkage while both
/// members are still unplaced: a leg that fills first then cancels the
/// sibling atomically, and a leg whose sibling already terminated is
/// rejected OCO_SIBLING_CANCEL_RACE on arrival (deterministic WAL order).
/// link_id is the OCO group identifier persisted as orders.oco_group_id.
type OcoLink struct {
	_tab flatbuffers.Table
}

func GetRootAsOcoLink(buf []byte, offset flatbuffers.UOffsetT) *OcoLink {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OcoLink{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OcoLink) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OcoLink) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OcoLink) LinkId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OcoLink) MutateLinkId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OcoLink) OrderIdA() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OcoLink) MutateOrderIdA(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *OcoLink) OrderIdB() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OcoLink) MutateOrderIdB(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *OcoLink) AccountId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OcoLink) MutateAccountId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *OcoLink) InstrumentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OcoLink) MutateInstrumentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func OcoLinkStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func OcoLinkAddLinkId(builder *flatbuffers.Builder, linkId uint64) {
	builder.PrependUint64Slot(0, linkId, 0)
}
func OcoLinkAddOrderIdA(builder *flatbuffers.Builder, orderIdA uint64) {
	builder.PrependUint64Slot(1, orderIdA, 0)
}
func OcoLinkAddOrderIdB(builder *flatbuffers.Builder, orderIdB uint64) {
	builder.PrependUint64Slot(2, orderIdB, 0)
}
func OcoLinkAddAccountId(builder *flatbuffers.Builder, accountId uint64) {
	builder.PrependUint64Slot(3, accountId, 0)
}
func OcoLinkAddInstrumentId(builder *flatbuffers.Builder, instrumentId uint32) {
	builder.PrependUint32Slot(4, instrumentId, 0)
}
func OcoLinkEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
