// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type OrderType byte

const (
	OrderTypeMarket     OrderType = 0
	OrderTypeLimit      OrderType = 1
	OrderTypeStopMarket OrderType = 2
	OrderTypeStopLimit  OrderType = 3
	OrderTypeIceberg    OrderType = 4
	OrderTypePeg        OrderType = 5
	OrderTypeFixing     OrderType = 6
)

var EnumNamesOrderType = map[OrderType]string{
	OrderTypeMarket:     "Market",
	OrderTypeLimit:      "Limit",
	OrderTypeStopMarket: "StopMarket",
	OrderTypeStopLimit:  "StopLimit",
	OrderTypeIceberg:    "Iceberg",
	OrderTypePeg:        "Peg",
	OrderTypeFixing:     "Fixing",
}

var EnumValuesOrderType = map[string]OrderType{
	"Market":     OrderTypeMarket,
	"Limit":      OrderTypeLimit,
	"StopMarket": OrderTypeStopMarket,
	"StopLimit":  OrderTypeStopLimit,
	"Iceberg":    OrderTypeIceberg,
	"Peg":        OrderTypePeg,
	"Fixing":     OrderTypeFixing,
}

func (v OrderType) String() string {
	if s, ok := EnumNamesOrderType[v]; ok {
		return s
	}
	return "OrderType(" + strconv.FormatInt(int64(v), 10) + ")"
}
