// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Inbound: cancel request.
type OrderCancel struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderCancel(buf []byte, offset flatbuffers.UOffsetT) *OrderCancel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderCancel{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OrderCancel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderCancel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderCancel) OrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderCancel) MutateOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OrderCancel) AccountId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderCancel) MutateAccountId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func OrderCancelStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OrderCancelAddOrderId(builder *flatbuffers.Builder, orderId uint64) {
	builder.PrependUint64Slot(0, orderId, 0)
}
func OrderCancelAddAccountId(builder *flatbuffers.Builder, accountId uint64) {
	builder.PrependUint64Slot(1, accountId, 0)
}
func OrderCancelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
