// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Inbound: order submission from the Go gateway to the matching core.
/// Phase-02 extension fields are additive (FlatBuffers table append —
/// old writers still decode, new fields default 0).
type OrderNew struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderNew(buf []byte, offset flatbuffers.UOffsetT) *OrderNew {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderNew{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OrderNew) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderNew) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderNew) OrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OrderNew) AccountId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateAccountId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *OrderNew) InstrumentId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateInstrumentId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *OrderNew) Side() Side {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return Side(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OrderNew) MutateSide(n Side) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

func (rcv *OrderNew) Type() OrderType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return OrderType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OrderNew) MutateType(n OrderType) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func (rcv *OrderNew) Qty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *OrderNew) Price() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutatePrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *OrderNew) Tif() TimeInForce {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return TimeInForce(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OrderNew) MutateTif(n TimeInForce) bool {
	return rcv._tab.MutateByteSlot(18, byte(n))
}

func (rcv *OrderNew) ClientOrderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OrderNew) StpMode() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateStpMode(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

func (rcv *OrderNew) Flags() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateFlags(n byte) bool {
	return rcv._tab.MutateByteSlot(24, n)
}

func (rcv *OrderNew) StopPrice() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateStopPrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(26, n)
}

func (rcv *OrderNew) GtdExpiryNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateGtdExpiryNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(28, n)
}

func (rcv *OrderNew) DisplayQty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateDisplayQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(30, n)
}

func (rcv *OrderNew) TradeGroupId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateTradeGroupId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(32, n)
}

func (rcv *OrderNew) DiscretionaryOffsetPips() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderNew) MutateDiscretionaryOffsetPips(n int64) bool {
	return rcv._tab.MutateInt64Slot(34, n)
}

func OrderNewStart(builder *flatbuffers.Builder) {
	builder.StartObject(16)
}
func OrderNewAddOrderId(builder *flatbuffers.Builder, orderId uint64) {
	builder.PrependUint64Slot(0, orderId, 0)
}
func OrderNewAddAccountId(builder *flatbuffers.Builder, accountId uint64) {
	builder.PrependUint64Slot(1, accountId, 0)
}
func OrderNewAddInstrumentId(builder *flatbuffers.Builder, instrumentId uint32) {
	builder.PrependUint32Slot(2, instrumentId, 0)
}
func OrderNewAddSide(builder *flatbuffers.Builder, side Side) {
	builder.PrependByteSlot(3, byte(side), 0)
}
func OrderNewAddType(builder *flatbuffers.Builder, type_ OrderType) {
	builder.PrependByteSlot(4, byte(type_), 0)
}
func OrderNewAddQty(builder *flatbuffers.Builder, qty int64) {
	builder.PrependInt64Slot(5, qty, 0)
}
func OrderNewAddPrice(builder *flatbuffers.Builder, price int64) {
	builder.PrependInt64Slot(6, price, 0)
}
func OrderNewAddTif(builder *flatbuffers.Builder, tif TimeInForce) {
	builder.PrependByteSlot(7, byte(tif), 0)
}
func OrderNewAddClientOrderId(builder *flatbuffers.Builder, clientOrderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(clientOrderId), 0)
}
func OrderNewAddStpMode(builder *flatbuffers.Builder, stpMode byte) {
	builder.PrependByteSlot(9, stpMode, 0)
}
func OrderNewAddFlags(builder *flatbuffers.Builder, flags byte) {
	builder.PrependByteSlot(10, flags, 0)
}
func OrderNewAddStopPrice(builder *flatbuffers.Builder, stopPrice int64) {
	builder.PrependInt64Slot(11, stopPrice, 0)
}
func OrderNewAddGtdExpiryNs(builder *flatbuffers.Builder, gtdExpiryNs int64) {
	builder.PrependInt64Slot(12, gtdExpiryNs, 0)
}
func OrderNewAddDisplayQty(builder *flatbuffers.Builder, displayQty int64) {
	builder.PrependInt64Slot(13, displayQty, 0)
}
func OrderNewAddTradeGroupId(builder *flatbuffers.Builder, tradeGroupId uint32) {
	builder.PrependUint32Slot(14, tradeGroupId, 0)
}
func OrderNewAddDiscretionaryOffsetPips(builder *flatbuffers.Builder, discretionaryOffsetPips int64) {
	builder.PrependInt64Slot(15, discretionaryOffsetPips, 0)
}
func OrderNewEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
