// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type OrderType byte

const (
	OrderTypeMarket     OrderType = 0
	OrderTypeLimit      OrderType = 1
	OrderTypeStopMarket OrderType = 2
	OrderTypeStopLimit  OrderType = 3
)

var EnumNamesOrderType = map[OrderType]string{
	OrderTypeMarket:     "Market",
	OrderTypeLimit:      "Limit",
	OrderTypeStopMarket: "StopMarket",
	OrderTypeStopLimit:  "StopLimit",
}

var EnumValuesOrderType = map[string]OrderType{
	"Market":     OrderTypeMarket,
	"Limit":      OrderTypeLimit,
	"StopMarket": OrderTypeStopMarket,
	"StopLimit":  OrderTypeStopLimit,
}

func (v OrderType) String() string {
	if s, ok := EnumNamesOrderType[v]; ok {
		return s
	}
	return "OrderType(" + strconv.FormatInt(int64(v), 10) + ")"
}
