// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Inbound: cancel request.
/// `reason` is additive (Phase-14 Task 14.3.1): engine-emitted outbound
/// cancels carry the kWalCancelReason* code (0=user, 1=expired, 2=STP,
/// 3=FOK_unfilled, 4=IOC_remainder, 5=slippage, 6=exec-rule range,
/// 7=OCO sibling) so the read model can distinguish a sibling-cancelled
/// OCO leg for the OCO_SIBLING_CANCEL_RACE (409) API mapping. Inbound
/// cancel requests leave it 0/unset.
type OrderCancel struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderCancel(buf []byte, offset flatbuffers.UOffsetT) *OrderCancel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderCancel{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OrderCancel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderCancel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderCancel) OrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderCancel) MutateOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OrderCancel) AccountId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderCancel) MutateAccountId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *OrderCancel) Reason() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderCancel) MutateReason(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func OrderCancelStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func OrderCancelAddOrderId(builder *flatbuffers.Builder, orderId uint64) {
	builder.PrependUint64Slot(0, orderId, 0)
}
func OrderCancelAddAccountId(builder *flatbuffers.Builder, accountId uint64) {
	builder.PrependUint64Slot(1, accountId, 0)
}
func OrderCancelAddReason(builder *flatbuffers.Builder, reason byte) {
	builder.PrependByteSlot(2, reason, 0)
}
func OrderCancelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
