// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Inbound: atomic amend/replace (Task 2.3.20). Single-thread total order —
// / concurrent amends on the same order_seq resolve to exactly one winner.
type OrderAmend struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderAmend(buf []byte, offset flatbuffers.UOffsetT) *OrderAmend {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderAmend{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OrderAmend) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderAmend) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderAmend) OrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderAmend) MutateOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *OrderAmend) OrderSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderAmend) MutateOrderSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *OrderAmend) Price() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderAmend) MutatePrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *OrderAmend) Qty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderAmend) MutateQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *OrderAmend) StopPrice() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderAmend) MutateStopPrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *OrderAmend) GtdExpiryNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OrderAmend) MutateGtdExpiryNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func OrderAmendStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func OrderAmendAddOrderId(builder *flatbuffers.Builder, orderId uint64) {
	builder.PrependUint64Slot(0, orderId, 0)
}
func OrderAmendAddOrderSeq(builder *flatbuffers.Builder, orderSeq uint64) {
	builder.PrependUint64Slot(1, orderSeq, 0)
}
func OrderAmendAddPrice(builder *flatbuffers.Builder, price int64) {
	builder.PrependInt64Slot(2, price, 0)
}
func OrderAmendAddQty(builder *flatbuffers.Builder, qty int64) {
	builder.PrependInt64Slot(3, qty, 0)
}
func OrderAmendAddStopPrice(builder *flatbuffers.Builder, stopPrice int64) {
	builder.PrependInt64Slot(4, stopPrice, 0)
}
func OrderAmendAddGtdExpiryNs(builder *flatbuffers.Builder, gtdExpiryNs int64) {
	builder.PrependInt64Slot(5, gtdExpiryNs, 0)
}
func OrderAmendEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
