// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// One aggregated price level within a BookSnapshot.
type PriceLevel struct {
	_tab flatbuffers.Table
}

func GetRootAsPriceLevel(buf []byte, offset flatbuffers.UOffsetT) *PriceLevel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PriceLevel{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PriceLevel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PriceLevel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PriceLevel) Price() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PriceLevel) MutatePrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *PriceLevel) Qty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PriceLevel) MutateQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *PriceLevel) Count() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PriceLevel) MutateCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func PriceLevelStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PriceLevelAddPrice(builder *flatbuffers.Builder, price int64) {
	builder.PrependInt64Slot(0, price, 0)
}
func PriceLevelAddQty(builder *flatbuffers.Builder, qty int64) {
	builder.PrependInt64Slot(1, qty, 0)
}
func PriceLevelAddCount(builder *flatbuffers.Builder, count uint32) {
	builder.PrependUint32Slot(2, count, 0)
}
func PriceLevelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
