// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type Side byte

const (
	SideBuy  Side = 0
	SideSell Side = 1
)

var EnumNamesSide = map[Side]string{
	SideBuy:  "Buy",
	SideSell: "Sell",
}

var EnumValuesSide = map[string]Side{
	"Buy":  SideBuy,
	"Sell": SideSell,
}

func (v Side) String() string {
	if s, ok := EnumNamesSide[v]; ok {
		return s
	}
	return "Side(" + strconv.FormatInt(int64(v), 10) + ")"
}
