// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Inbound: deterministic clock tick (Task 2.3.10). The matching thread turns
/// each tick into a WAL TIME_TICK entry — the gateway never writes the WAL.
type TimeTick struct {
	_tab flatbuffers.Table
}

func GetRootAsTimeTick(buf []byte, offset flatbuffers.UOffsetT) *TimeTick {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimeTick{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TimeTick) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimeTick) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimeTick) TickNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TimeTick) MutateTickNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func TimeTickStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TimeTickAddTickNs(builder *flatbuffers.Builder, tickNs uint64) {
	builder.PrependUint64Slot(0, tickNs, 0)
}
func TimeTickEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
