// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import "strconv"

type TimeInForce byte

const (
	TimeInForceGTC TimeInForce = 0
	TimeInForceIOC TimeInForce = 1
	TimeInForceFOK TimeInForce = 2
	TimeInForceGTD TimeInForce = 3
	TimeInForceDAY TimeInForce = 4
)

var EnumNamesTimeInForce = map[TimeInForce]string{
	TimeInForceGTC: "GTC",
	TimeInForceIOC: "IOC",
	TimeInForceFOK: "FOK",
	TimeInForceGTD: "GTD",
	TimeInForceDAY: "DAY",
}

var EnumValuesTimeInForce = map[string]TimeInForce{
	"GTC": TimeInForceGTC,
	"IOC": TimeInForceIOC,
	"FOK": TimeInForceFOK,
	"GTD": TimeInForceGTD,
	"DAY": TimeInForceDAY,
}

func (v TimeInForce) String() string {
	if s, ok := EnumNamesTimeInForce[v]; ok {
		return s
	}
	return "TimeInForce(" + strconv.FormatInt(int64(v), 10) + ")"
}
