// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wire

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Outbound: execution report emitted by the matching core.
type TradeFill struct {
	_tab flatbuffers.Table
}

func GetRootAsTradeFill(buf []byte, offset flatbuffers.UOffsetT) *TradeFill {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TradeFill{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TradeFill) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TradeFill) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TradeFill) TradeId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeFill) MutateTradeId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *TradeFill) BuyOrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeFill) MutateBuyOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *TradeFill) SellOrderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeFill) MutateSellOrderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *TradeFill) Price() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeFill) MutatePrice(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *TradeFill) Qty() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeFill) MutateQty(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *TradeFill) Seq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TradeFill) MutateSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func TradeFillStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func TradeFillAddTradeId(builder *flatbuffers.Builder, tradeId uint64) {
	builder.PrependUint64Slot(0, tradeId, 0)
}
func TradeFillAddBuyOrderId(builder *flatbuffers.Builder, buyOrderId uint64) {
	builder.PrependUint64Slot(1, buyOrderId, 0)
}
func TradeFillAddSellOrderId(builder *flatbuffers.Builder, sellOrderId uint64) {
	builder.PrependUint64Slot(2, sellOrderId, 0)
}
func TradeFillAddPrice(builder *flatbuffers.Builder, price int64) {
	builder.PrependInt64Slot(3, price, 0)
}
func TradeFillAddQty(builder *flatbuffers.Builder, qty int64) {
	builder.PrependInt64Slot(4, qty, 0)
}
func TradeFillAddSeq(builder *flatbuffers.Builder, seq uint64) {
	builder.PrependUint64Slot(5, seq, 0)
}
func TradeFillEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
